version: 2.0
jobs:
  build:
    docker:
     - image: eladb/superchain
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - run:
          name: package
          command: npm run package
