version: 2.0
jobs:
  build:
    docker:
     - image: image: circleci/node:9.8
    steps:
      - checkout
      - run:
          name: install
          command: |
            npm install
      - run:
          name: build
          command: |
            npm run build
      - run:
          name: test
          command: |
            npm test
