version: 2.0
jobs:
  build:
    docker:
     - image: jsii/superchain
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - run:
          name: package
          command: npm run package
      - run:
          name: publish to npm
          command: npx jsii-release-npm dist/js
      - run:
          name: publish to pypi
          command: npx jsii-release-pypi dist/python
